### ISSUE TITLE
Cannot start stream

### ISSUE THREAD

**Issue by hmtxz** [ewwink/OBS-with-RTMPS-SSL-TLS#1]
Can't start stream, I think because no option in Bind IP
![bug](https://cloud.githubusercontent.com/assets/20640272/21537875/295d8006-cdc9-11e6-91e8-aa1f0530a64a.PNG)

And latest version please

**Comment by ewwink** [comment]
have you install "Visual C++ Redistributable for Visual Studio 2015" ? 
and post your logs file, **Help > Log Files > Show Log Files**
it work fine in my PC


![obs-ssl](https://cloud.githubusercontent.com/assets/760764/21541414/ad320202-cde8-11e6-8aeb-2ecf51570dbb.jpg)

**Comment by hmtxz** [comment]
already installed

My log:
07:58:14.851: CPU Name: Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz
07:58:14.852: CPU Speed: 2195MHz
07:58:14.852: Physical Cores: 2, Logical Cores: 4
07:58:14.852: Physical Memory: 4000MB Total, 2010MB Free
07:58:14.852: Windows Version: 10.0 Build 14393 (revision: 0; 64-bit)
07:58:14.852: Running as administrator: true
07:58:14.852: Aero is Enabled (Aero is always on for windows 8 and above)
07:58:14.853: Portable mode: false
07:58:14.873: OBS 0.16.6-15-g7df46d4a-modified (64bit, windows)
07:58:14.873: ---------------------------------
07:58:14.874: ---------------------------------
07:58:14.874: audio settings reset:
07:58:14.874: 	samples per sec: 44100
07:58:14.874: 	speakers:        2
07:58:14.877: ---------------------------------
07:58:14.877: Initializing D3D11..
07:58:14.877: Available Video Adapters: 
07:58:14.879: 	Adapter 1: Intel(R) HD Graphics 3000
07:58:14.879: 	  Dedicated VRAM: 33554432
07:58:14.879: 	  Shared VRAM:    1711276032
07:58:14.879: 	  output 1: pos={0, 0}, size={1366, 768}, attached=true
07:58:14.882: Loading up D3D11 on adapter Intel(R) HD Graphics 3000 (0)
07:58:14.885: D3D11 loaded sucessfully, feature level used: 41216
07:58:16.073: ---------------------------------
07:58:16.073: video settings reset:
07:58:16.073: 	base resolution:   1366x768
07:58:16.073: 	output resolution: 1092x614
07:58:16.073: 	downscale filter:  Bicubic
07:58:16.073: 	fps:               30/1
07:58:16.073: 	format:            NV12
07:58:16.074: ---------------------------------
07:58:16.078: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
07:58:16.086: LoadLibrary failed for 'nvEncodeAPI64.dll': The specified module could not be found.
07:58:16.086:  (126)
07:58:16.089: LoadLibrary failed for '../../obs-plugins/64bit/obs-outputs.dll': The specified module could not be found.
07:58:16.089:  (126)
07:58:16.089: Module '../../obs-plugins/64bit/obs-outputs.dll' not found
07:58:16.551: No blackmagic support
07:58:16.708: load_graphics_offsets: Failed to start 'get-graphics-offsets32.exe'
07:58:16.794: ---------------------------------
07:58:16.794:   Loaded Modules:
07:58:16.794:     win-wasapi.dll
07:58:16.794:     win-mf.dll
07:58:16.794:     win-dshow.dll
07:58:16.794:     win-decklink.dll
07:58:16.794:     win-capture.dll
07:58:16.794:     text-freetype2.dll
07:58:16.794:     rtmp-services.dll
07:58:16.794:     obs-x264.dll
07:58:16.794:     obs-transitions.dll
07:58:16.794:     obs-text.dll
07:58:16.794:     obs-qsv11.dll
07:58:16.794:     obs-filters.dll
07:58:16.794:     obs-ffmpeg.dll
07:58:16.794:     image-source.dll
07:58:16.794:     frontend-tools.dll
07:58:16.794:     coreaudio-encoder.dll
07:58:16.794: ==== Startup complete ===============================================
07:58:16.795: Output ID 'rtmp_output' not found
07:58:16.795: Failed to create output 'simple_stream'!
07:58:16.795: Service '' not found
07:58:16.832: All scene data cleared
07:58:16.832: ------------------------------------------------
07:58:16.898: WASAPI: Device 'Speakers (Realtek High Definition Audio)' initialized
07:58:16.923: WASAPI: Device 'Microphone (Realtek High Definition Audio)' initialized
07:58:16.924: Switched to scene 'Scene'
07:58:16.924: ------------------------------------------------
07:58:16.925: Loaded scenes:
07:58:16.925: - scene 'Scene':
07:58:16.925: ------------------------------------------------
07:58:16.956: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds
07:58:20.046: rtmp-common.c: [initialize_output] Could not find service ''
07:58:20.048: rtmp-common.c: [initialize_output] Could not find service ''
07:58:20.101: rtmp-common.c: [initialize_output] Could not find service ''
07:58:20.880: rtmp-common.c: [initialize_output] Could not find service ''

**Comment by ewwink** [comment]
did you get error message about missing SSLEAY32.dll?
if yes download OpenSSL http://indy.fulgan.com/SSL/openssl-1.0.2i-x64_86-win64.zip and exctract libeay32.dll and ssleay32.dll to executable directory or Systems32.
