### ISSUE TITLE
a small request

### ISSUE THREAD

**Issue by TMHBOFH** [ewwink/OBS-with-RTMPS-SSL-TLS#2]
Hi ewwink,

at first **big thanks** for the great job!!!

Would be possible to port the RTMPS-SSL-TLS function to the new OBS-Studio version 18.0.1?

Best regards

**Comment by ewwink** [comment]
Hi @TMHBOFH I have added 18.0.1 win32 check release page https://github.com/ewwink/OBS-with-RTMPS-SSL-TLS/releases

**Comment by TMHBOFH** [comment]
Hi ewwink,

**BIG THANKS** for the quick release of new version. It works very well.
If you have time, it would by nice when you can create a 64Bit version.

best regards and nice weekend
