### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by hmtxz** [ewwink/OBS-with-RTMPS-SSL-TLS#3]
Can you make it available fo linux? or can you tell me to build obs with ssl support on linux?

Thanks

**Comment by ewwink** [comment]
untuk linux sudah ada caranya, tidak usah edit CMakeLists.txt cukup tambahkan `-DUSE_SSL=on`
https://github.com/ewwink/OBS-with-RTMPS-SSL-TLS#compile-obs-linux-with-rtmps-support
